### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jaikishantulswani** [Den1al/pyfindsubdomains#2]
Getting this after installation

toor@kali:~$ findsubdomains --help
Traceback (most recent call last):
  File "/usr/local/bin/findsubdomains", line 11, in <module>
    load_entry_point('pyfindsubdomains==0.0.2.3', 'console_scripts', 'findsubdomains')()
  File "/home/toor/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/toor/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/toor/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/toor/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-i686/egg/findsubdomains/cli.py", line 12, in <module>
ImportError: No module named pathlib

**Comment by Den1al** [comment]
Hi, thanks for the input. Please install the "pathlib" module using:
```
pip install pathlib
```

Then the script should work fine.

**Comment by jaikishantulswani** [comment]
Thank you :+1:
